package main

import "fmt"


func fibonacci() int(a){
   a, b = 0
   return func(){
    
    }
}

func main(){
   for i:= 0; i<1000; i++{
      //call the fibonacci function i times
}
}


// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the 
// previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose 
// values do not exceed four million, find the sum of the even-valued terms.


//Solution

// solved by using a fibonacci generator (with a closures) 
// then adding up the values

// Other posible solutions:


